# Generated by Django 5.2.17 on 2026-08-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airbnb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-location"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=150)),
                ("university", models.CharField(max_length=150)),
                (
                    "room_type",
                    models.CharField(
                        choices=[("single", "Single"), ("double", "Double")],
                        max_length=10,
                    ),
                ),
                ("self_contained", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-location"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=150)),
                (
                    "room_type",
                    models.CharField(
                        choices=[("single", "Single"), ("double", "Double")],
                        max_length=10,
                    ),
                ),
                ("self_contained", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-location"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AirbnbImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="units/%Y/%m/")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to set this image as the main display photo.",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="your_room.airbnb",
                    ),
                ),
            ],
            options={
                "ordering": ["is_main"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HostelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="units/%Y/%m/")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to set this image as the main display photo.",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="your_room.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ["is_main"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="units/%Y/%m/")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to set this image as the main display photo.",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="your_room.rental",
                    ),
                ),
            ],
            options={
                "ordering": ["is_main"],
                "abstract": False,
            },
        ),
    ]
