# Generated by Django 5.2.17 on 2026-08-20 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airbnb",
            options={"ordering": ["location"]},
        ),
        migrations.AlterModelOptions(
            name="hostel",
            options={"ordering": ["location"]},
        ),
        migrations.AlterModelOptions(
            name="rental",
            options={"ordering": ["location"]},
        ),
    ]
