# Generated by Django 5.2.17 on 2026-08-20 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0002_alter_airbnb_options_alter_hostel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airbnb",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="hostel",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="rental",
            options={"ordering": ["name"]},
        ),
    ]
