# Generated by Django 5.2.17 on 2026-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0005_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
