# Generated by Django 5.2.17 on 2026-09-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0007_lessorcustodian"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessorCustodian",
            new_name="AirbnbLessor",
        ),
        migrations.CreateModel(
            name="HostelLessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custodian",
                        to="your_room.hostel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalLessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custodian",
                        to="your_room.rental",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
