# Generated by Django 5.2.17 on 2026-09-07 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0008_rename_lessorcustodian_airbnblessor_hostellessor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="hostellessor",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="rentallessor",
            name="unit",
        ),
        migrations.AddField(
            model_name="airbnb",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="airbnbs",
                to="your_room.lessor",
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hostels",
                to="your_room.lessor",
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rentals",
                to="your_room.lessor",
            ),
        ),
        migrations.DeleteModel(
            name="AirbnbLessor",
        ),
        migrations.DeleteModel(
            name="HostelLessor",
        ),
        migrations.DeleteModel(
            name="RentalLessor",
        ),
    ]
