# Generated by Django 5.2.17 on 2026-09-07 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0009_lessor_remove_hostellessor_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airbnb",
            old_name="custodian",
            new_name="landlord",
        ),
        migrations.RenameField(
            model_name="rental",
            old_name="custodian",
            new_name="landlord",
        ),
    ]
