# Generated by Django 5.2.17 on 2026-09-07 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0010_rename_custodian_airbnb_landlord_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airbnb",
            old_name="landlord",
            new_name="lessor",
        ),
        migrations.RenameField(
            model_name="hostel",
            old_name="custodian",
            new_name="lessor",
        ),
        migrations.RenameField(
            model_name="rental",
            old_name="landlord",
            new_name="lessor",
        ),
    ]
