# Generated by Django 5.2.17 on 2026-09-14 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0011_rename_landlord_airbnb_lessor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airbnb",
            name="description",
        ),
        migrations.RemoveField(
            model_name="hostel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="description",
        ),
    ]
