# Generated by Django 5.2.4 on 2026-09-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0013_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="units/%Y/%m/")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to set this image as the main display photo.",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="your_room.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["is_main"],
                "abstract": False,
            },
        ),
    ]
