# Generated by Django 5.2.17 on 2026-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0014_hotelimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="airbnb",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe the unit: facilities, rules, nearby places, etc.",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe the unit: facilities, rules, nearby places, etc.",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe the unit: facilities, rules, nearby places, etc.",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe the unit: facilities, rules, nearby places, etc.",
                max_length=2000,
            ),
        ),
    ]
