# Generated by Django 5.2.17 on 2026-10-02 12:28

import django.core.validators
import django.db.models.deletion
import your_room.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_room", "0015_airbnb_description_hostel_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirbnbVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="MP4 recommended, under 30MB, ideally 30-60 seconds.",
                        upload_to="unit_videos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "mov"]
                            ),
                            your_room.models.validate_video_size,
                        ],
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="your_room.airbnb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HostelVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="MP4 recommended, under 30MB, ideally 30-60 seconds.",
                        upload_to="unit_videos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "mov"]
                            ),
                            your_room.models.validate_video_size,
                        ],
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="your_room.hostel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HotelVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="MP4 recommended, under 30MB, ideally 30-60 seconds.",
                        upload_to="unit_videos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "mov"]
                            ),
                            your_room.models.validate_video_size,
                        ],
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="your_room.hotel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="MP4 recommended, under 30MB, ideally 30-60 seconds.",
                        upload_to="unit_videos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "mov"]
                            ),
                            your_room.models.validate_video_size,
                        ],
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="your_room.rental",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
